## Loading Datasets





In [8]:
import numpy as np
import pandas as pd
import pickle
filename="heart.csv"

## Pandas to read csv file

In [9]:
df=pd.read_csv(filename)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [10]:
##Selects the top head 5 rows
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

## Numpys load txt and gen from textdata 

In [20]:
data=np.loadtxt(filename,delimiter=",",skiprows=1) ##Skip 1 row because low loadtext assumes homogenous structure .Here everything is a float
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [26]:
#If we want column names we can use genfromtext. We produce a list of tuples
data=np.genfromtxt(filename,delimiter=",",dtype=None,names=True,encoding="utf-8-sig")
print(data)
print(data.dtype)

[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 3, 150, 283, 1, 0, 162, 0, 1. , 2, 0, 2, 1)
 (50, 0, 2, 120, 219, 0, 1, 158, 0, 1.6, 1, 0, 2, 1)
 (58, 0, 2, 120, 340, 0, 1, 172, 0, 0. , 2, 0, 2, 1)
 (66, 0, 3, 150, 226, 0, 1, 114, 0, 2.6, 0, 0, 2, 1)
 (43, 1, 0, 150, 247, 0, 1, 171, 0, 1.5, 2, 0,

In [28]:
## Reading Messy files
def load_file(filename):
    with open(filename, encoding="utf-8-sig") as f:
        data, cols = [], []
        for i, line in enumerate(f.read().splitlines()):
            if i == 0:
                cols += line.split(",")
            else:
                data.append([float(x) for x in line.split(",")])
        df = pd.DataFrame(data, columns=cols)
    return df
load_file(filename).head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0    0.0      0.8   
4  57.0  0.0  0.0     120.0  354.0  0.0      1.0    163.0    1.0      0.6   

   slope   ca  thal  target  
0    0.0  0.0   1.0     1.0  
1    0.0  0.0   2.0     1.0  
2    2.0  0.0   2.0     1.0  
3    2.0  0.0   2.0     1.0  
4    2.0  0.0   2.0     1.0

##  We can use also Pickles which is faster for large amount of data


## Numpy vs Pandas

In [32]:
## 1) Pandas has a numpy core
## 2) Extra structure and tools but sometimes you have to strip it away

In [35]:
data=df.to_numpy()
data 

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [36]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [38]:
print(data.dtype,data) ##to numpy has converted everything to a float. If we want to preserve the datatypes we have to use loops.

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [41]:
data[0, 0] = 100
df.head()
# Notice it doesnt modify the original data frame here

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [43]:
# But we can still explicitly call copy if we wanted
df2 = df[["age", "sex", "cp"]]
data2 = df2.to_numpy().copy()
data2[0, 0] = 100
df2

age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [44]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [45]:
df.age.to_numpy()[0] = 100
df
# Here it DOES modify the original, because to_numpy hasnt needed to make a new array
# so our reference is to the original, underlying data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    100    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [46]:
# Many functions you can do in both pandas and numpy
print(df['age'].mean(), df['age'].to_numpy().mean())

54.48844884488449 54.48844884488449


In [47]:
# Some are pandas only
print(df['age'].quantile(0.5))
# print(df['age'].to_numpy().quantile(0.5))

55.0


In [48]:
# And some are numpy only
# print(df['age'].reshape((3, -1)))
print(df['age'].to_numpy().reshape((3, -1)))

[[100  37  41  56  57  57  56  44  52  57  54  48  49  64  58  50  58  66
   43  69  59  44  42  61  40  71  59  51  65  53  41  65  44  54  51  46
   54  54  65  65  51  48  45  53  39  52  44  47  53  53  51  66  62  44
   63  52  48  45  34  57  71  54  52  41  58  35  51  45  44  62  54  51
   29  51  43  55  51  59  52  58  41  45  60  52  42  67  68  46  54  58
   48  57  52  54  45  53  62  52  43  53  42]
 [ 59  63  42  50  68  69  45  50  50  64  57  64  43  55  37  41  56  46
   46  64  59  41  54  39  34  47  67  52  74  54  49  42  41  41  49  60
   62  57  64  51  43  42  67  76  70  44  60  44  42  66  71  64  66  39
   58  47  35  58  56  56  55  41  38  38  67  67  62  63  53  56  48  58
   58  60  40  60  64  43  57  55  65  61  58  50  44  60  54  50  41  51
   58  54  60  60  59  46  67  62  65  44  60]
 [ 58  68  62  52  59  60  49  59  57  61  39  61  56  43  62  63  65  48
   63  55  65  56  54  70  62  35  59  64  47  57  55  64  70  51  58  60
   77  35  70  59 

## Rules: 
Work with pandas as much as you can, more functionality
Sometimes you need to get the actual array, and use to_numpy()

###  Different Types of Files:

In [50]:
df=pd.read_csv("astronauts.csv")
df.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired  5/20/1951  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired  1/20/1930  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                              STS 51-F (Challenger)        NaN           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaN           NaN  
4                               Gemini 12, Apollo 11        NaN           NaN

In [51]:
##Save to different formats
df.to_csv("save.csv", index=False, float_format="%0.4f")

In [53]:
pd.read_csv("save.csv")

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           

In [54]:
df.to_pickle("save.pkl")

In [56]:
pd.read_pickle("save.pkl")

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           

In [57]:
df.to_hdf("save.hdf", key="data", format="table")

In [58]:
pd.read_hdf("save.hdf");

In [61]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is E040-A4A3

 Directory of C:\Users\†Άε��\Desktop\Jupyter DataManipulation

06/26/2022  05:10 PM    <DIR>          .
06/26/2022  05:10 PM    <DIR>          ..
06/26/2022  02:45 PM    <DIR>          .ipynb_checkpoints
09/20/2019  03:04 AM            81,593 astronauts.csv
06/26/2022  05:10 PM           120,446 DataImport.ipynb
10/01/2019  01:15 PM            11,328 heart.csv
06/26/2022  05:08 PM            87,030 save.csv
06/26/2022  05:10 PM           801,641 save.hdf
06/26/2022  05:09 PM            90,746 save.pkl
               6 File(s)      1,192,784 bytes
               3 Dir(s)  43,317,870,592 bytes free


# RECAP 

In terms of file size, HDF5 is the largest for this example. Everything else is approximately equal. For small data sizes, often csv is the easiest as its human readable. HDF5 is great for loading in huge amounts of data quickly. Pickle is faster than CSV, but not human readable.

Lots of options, don't get hung up on any of them. csv and pickle are easy and for most cases work fine.

## Inspecting DATA

In [62]:
df=pd.read_csv("astronauts.csv")

In [63]:
df.head(2)

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0  Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1   Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   

                                          Alma Mater  Undergraduate Major  \
0  University of California-Santa Barbara; Univer...              Geology   
1   Montana State University; University of Colorado  Engineering Physics   

  Graduate Major Military Rank Military Branch  Space Flights  \
0        Geology           NaN             NaN              2   
1  Solar Physics           NaN             NaN              1   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   

                                 Missions Death Date Death Mission  
0  STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                   STS 51-F (Challenger)        NaN           NaN

In [64]:
df.tail()

Name    Year  Group   Status Birth Date  \
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [65]:
df.tail(1)

Name    Year  Group   Status Birth Date      Birth Place  \
356  George D. Zamka  1998.0   17.0  Retired  6/29/1962  Jersey City, NJ   

    Gender                                         Alma Mater  \
356   Male  US Naval Academy; Florida Institute of Technology   

    Undergraduate Major          Graduate Major Military Rank  \
356         Mathematics  Engineering Management       Colonel   

               Military Branch  Space Flights  Space Flight (hr)  Space Walks  \
356  US Marine Corps (Retired)              2                692            0   

     Space Walks (hr)                                 Missions Death Date  \
356               0.0  STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
356           NaN

In [66]:
df.sample(3)

Name    Year  Group   Status  Birth Date      Birth Place  \
166  Michael S. Hopkins  2009.0   20.0   Active  12/28/1968      Lebanon, MO   
110   William F. Fisher  1980.0    9.0  Retired    4/1/1946       Dallas, TX   
178  Gregory H. Johnson  1998.0   17.0   Active   5/12/1962  London, England   

    Gender                                         Alma Mater  \
166   Male        University of Illinois; Stanford University   
110   Male  Stanford University; University of Houston; Un...   
178   Male  US Air Force Academy; Columbia University; Uni...   

          Undergraduate Major  \
166     Aerospace Engineering   
110                       NaN   
178  Aeronautical Engineering   

                                        Graduate Major Military Rank  \
166                              Aerospace Engineering       Colonel   
110                              Engineering; Medicine           NaN   
178  Flight Structures Engineering; Business Admini...       Colonel   

            Military Branch  Space Flights  Space Flight (hr)  Space Walks  \
166            US Air Force              1               3990            2   
110                     NaN              1                170            2   
178  US Air Force (Retired)              2                755            0   

     Space Walks (hr)                                Missions Death Date  \
166              13.0                       ISS-37/38 (Soyuz)        NaN   
110              12.0                    STS 51-I (Discovery)        NaN   
178               0.0  STS-123 (Endeavor), STS-134 (Endeavor)        NaN   

    Death Mission  
166           NaN  
110           NaN  
178           NaN

In [67]:
df.info 

<bound method DataFrame.info of                       Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ

In [68]:
df.describe()

Year       Group  Space Flights  Space Flight (hr)  Space Walks  \
count   330.000000  330.000000     357.000000         357.000000   357.000000   
mean   1985.106061   11.409091       2.364146        1249.266106     1.246499   
std      13.216147    5.149962       1.428700        1896.759857     2.056989   
min    1959.000000    1.000000       0.000000           0.000000     0.000000   
25%    1978.000000    8.000000       1.000000         289.000000     0.000000   
50%    1987.000000   12.000000       2.000000         590.000000     0.000000   
75%    1996.000000   16.000000       3.000000        1045.000000     2.000000   
max    2009.000000   20.000000       7.000000       12818.000000    10.000000   

       Space Walks (hr)  
count        357.000000  
mean           7.707283  
std           13.367973  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           12.000000  
max           67.000000

In [70]:
df.shape

(357, 19)

In [71]:
df.corr()

Year     Group  Space Flights  Space Flight (hr)  \
Year               1.000000  0.980934       0.036420           0.331386   
Group              0.980934  1.000000      -0.011386           0.325683   
Space Flights      0.036420 -0.011386       1.000000           0.325233   
Space Flight (hr)  0.331386  0.325683       0.325233           1.000000   
Space Walks        0.210073  0.217891       0.257073           0.472796   
Space Walks (hr)   0.253502  0.261384       0.258642           0.454408   

                   Space Walks  Space Walks (hr)  
Year                  0.210073          0.253502  
Group                 0.217891          0.261384  
Space Flights         0.257073          0.258642  
Space Flight (hr)     0.472796          0.454408  
Space Walks           1.000000          0.985755  
Space Walks (hr)      0.985755          1.000000

In [72]:
df["Year"].value_counts()

1996.0    35
1978.0    35
1998.0    25
1990.0    23
1966.0    19
1995.0    19
1992.0    19
1980.0    19
1984.0    18
2000.0    17
1987.0    15
1963.0    14
1985.0    13
2004.0    11
1967.0    11
2009.0     9
1962.0     8
1959.0     7
1969.0     7
1965.0     6
Name: Year, dtype: int64

In [73]:
df.max()

Name                 Yvonne D. Cagle
Year                          2009.0
Group                           20.0
Status                       Retired
Birth Date                  9/9/1952
Birth Place              Yonkers, NY
Gender                          Male
Space Flights                      7
Space Flight (hr)              12818
Space Walks                       10
Space Walks (hr)                67.0
dtype: object